name: Generate and Deploy Docs

on:
  push:
    paths:
      - 'hello.py'  # Trigger only when hello.py changes
    branches:
      - main  # Adjust to your primary branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install sphinx

      - name: Generate Documentation
        run: |
          sphinx-apidoc -o docs/ .
          make -C docs html  # Ensure docs/Makefile exists

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
